server:
  port: 8081
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/student_management_system
    username: postgres
    password: malina
  mvc:
    throw-exception-if-no-handler-found: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
